In [295]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import json
import numpy as np

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_feature_film_series_with_two_entries"

In [3]:
r = requests.get(url)

In [4]:
soup = BeautifulSoup(r.text, 'html.parser')

In [138]:
#mix the soup
m = [item.get_text().split('\n') for item in soup.find_all('ol')]

In [353]:
#Quick function to query the OMDB API
def query_api(title, year):
    
    url = 'http://www.omdbapi.com'
    
    #Handle String years if necessary
    try:
        year = str(int(year))
    except:
        year = 'N/A'
    
    #Populate Params
    params = {'t': title,
           'y': year,
           'apikey': '13deb148'}
    
    #Make the request
    try:
        r = requests.get(url, params=params)
        print(r)

        json_text = json.loads(r.text)
        print(json_text)
    except:
        print(r)
        r = 0
    
    #Populate imdbRating
    try:
        imdb = json_text['imdbRating']
    except:
        imdb = 'N/A'
    
    #Populate Metascore Rating
    try:
        metascore = json_text['Metascore']
    except:
        metascore = 'N/A'
        
    #print(imdb, metascore)
    
    return {'imdb': imdb, 'metascore': metascore}

In [349]:
#[len(list(item.descendants)) for item in soup.find('div', {'class': 'div-col'}).find_all('i')]
'''
def names(item):
    #print(len(list(item.descendants)))
    return len(list(item.descendants)) == 1

unique_names = [item.text for item in list(filter(names, soup.find('div', {'class': 'div-col'}).find_all('i')))]
'''

"\ndef names(item):\n    #print(len(list(item.descendants)))\n    return len(list(item.descendants)) == 1\n\nunique_names = [item.text for item in list(filter(names, soup.find('div', {'class': 'div-col'}).find_all('i')))]\n"

In [243]:
#Set up the data structure

d = []

for i,item in enumerate(m):
    #uncomment the next line to query all, or adjust to query more
    if i < 50:
        #d[unique_names[i]] = []
        
        a = []

        for movie in item:
            mov = movie.split('(')

            try:
                movie_title = mov[0].strip()
                movie_year = int(mov[1].split(')')[0])
                
                if movie_year > 1990:
                
                    #query the API
                    api_data = query_api(movie_title, movie_year)

                    metascore = api_data['Metascore']
                    imdb = api_data['imdbRating']
                    #rotten_tomatoes = api_data['Ratings'][1]['Value'].split('%')[0]

                    #Build the dictionary
                    a.append({"movie": movie_title, 
                                 "year":movie_year, 
                                 'metascore': metascore, 
                                 'imdb': imdb, 
                                 'series': unique_names[i]})#, 
                                 #'rotten_tomatoes': rotten_tomatoes})
                    
                    
            except: pass
            
        d.append(a)

In [244]:
#Filter the list
#TODO: make this work for any length
def filterList(item):
    return len(item) == 2

clean_list = list(filter(filterList, d))

In [245]:
df = pd.DataFrame([item for sublist in clean_list for item in sublist])

In [246]:
df

,movie,year,metascore,imdb,series
0,2 Days in Paris,2007,67,6.8,2 Days in...
1,2 Days in New York,2012,61,6.0,2 Days in...
2,8mm,1999,19,6.5,8mm
3,8mm 2,2005,N/A,4.5,8mm
4,28 Days Later,2002,73,7.6,28 Days Later
5,28 Weeks Later,2007,78,7.0,28 Days Later
6,30 Days of Night,2007,53,6.6,30 Days of Night
7,30 Days of Night: Dark Days,2010,N/A,4.4,30 Days of Night
8,47 Meters Down,2017,52,5.6,47 Meters Down
9,47 Meters Down: Uncaged,2019,43,5.0,47 Meters Down
10,101 Dalmatians,1996,49,5.7,101 Dalmatians
11,102 Dalmatians,2000,35,4.9,101 Dalmatians
12,300,2007,N/A,7.5,101 Dalmatians
13,300: Rise of an Empire,2014,48,6.2,101 Dalmatians
14,500 Years Later,2005,N/A,6.8,300
15,Motherland,2010,N/A,8.0,300
16,666: The Child,2006,N/A,2.8,500 Years Later
17,666: The Beast,2007,N/A,2.7,500 Years Later
18,2001 Maniacs,2005,N/A,5.3,971-EVIL 2: The Astral Factor
19,2001 Maniacs: Field of Screams,2010,N/A,3.2,971-EVIL 2: The Astral Factor
20,A Dog's Purpose,2017,43,7.2,2001: A Space Odyssey
21,A Dog's Journey,2019,43,7.5,2001: A Space Odyssey
22,A Haunted House,2013,20,5.0,A Dog's Purpose
23,A Haunted House 2,2014,17,4.7,A Dog's Purpose
24,Ab Tak Chhappan,2004,N/A,7.8,Aashiqui
25,Ab Tak Chhappan 2,2015,N/A,5.8,Aashiqui
26,Abang Long Fadil,2014,N/A,6.7,Ab Tak Chhappan
27,Abang Long Fadil 2,2017,N/A,7.2,Ab Tak Chhappan
28,ABCD: Any Body Can Dance,2013,N/A,6.3,Abang Long Fadil
29,ABCD 2,2015,N/A,N/A,Abang Long Fadil
30,Agent Cody Banks,2003,41,5.0,Africa Express
31,Agent Cody Banks 2: Destination London,2004,32,4.6,Africa Express
32,Aksar,2006,N/A,4.8,Akaton mies
33,Aksar 2,2017,N/A,3.6,Akaton mies

In [ ]:
# Start of second try

In [258]:
l = [item.text.split('\n') for item in soup.find('div', {'class': 'div-col'}).find_all('li')]

In [263]:
def filterList(item):
    return len(item) == 3

clean_list = list(filter(filterList, l))

In [284]:
#TODO: refactor to work with more than 2 movies
titles = [[{'title':item[1], 'series': item[0]}, {'title':item[2], 'series':item[0]}] for item in clean_list]

In [285]:
df = pd.DataFrame([item for sublist in titles for item in sublist])

In [299]:
#Clean up the date column
def return_date(item):
    try:
        return item.split('(')[1].split(')')[0]
    except:
        return np.nan
    
df['date'] = df['title'].apply(lambda x:return_date(x))
df['title_clean'] = df['title'].apply(lambda x: x.split('(')[0])

In [300]:
df

,title,series,date,title_clean
0,00 Schneider – Jagd auf Nihil Baxter (1994),00 Schneider,1994,00 Schneider – Jagd auf Nihil Baxter
1,00 Schneider – Im Wendekreis der Eidechse [de]...,00 Schneider,2013,00 Schneider – Im Wendekreis der Eidechse [de]
2,2 Days in Paris (2007),2 Days in...,2007,2 Days in Paris
3,2 Days in New York (2012),2 Days in...,2012,2 Days in New York
4,8mm (1999),8mm,1999,8mm
...,...,...,...,...
3347,Zulu Dawn (1979) (prequel),Zulu,1979,Zulu Dawn
3348,Zuma (1985),Zuma,1985,Zuma
3349,Anak ni Zuma (1987),Zuma,1987,Anak ni Zuma
3350,Dschungelmädchen für zwei Halunken [de] (1974),Zwei Teufelskerle,1974,Dschungelmädchen für zwei Halunken [de]
3351,Zwei Teufelskerle auf dem Weg ins Kloster [de]...,Zwei Teufelskerle,1975,Zwei Teufelskerle auf dem Weg ins Kloster [de]

In [330]:
def convert_date(item):
    try:
        return int(item)
    except:
        return np.nan

df['date'] = df['date'].apply(lambda x: convert_date(x))

In [332]:
test_df = df.loc[df['date'] > 1990].head(20).copy()

In [333]:
test_df

,title,series,date,title_clean
0,00 Schneider – Jagd auf Nihil Baxter (1994),00 Schneider,1994.0,00 Schneider – Jagd auf Nihil Baxter
1,00 Schneider – Im Wendekreis der Eidechse [de]...,00 Schneider,2013.0,00 Schneider – Im Wendekreis der Eidechse [de]
2,2 Days in Paris (2007),2 Days in...,2007.0,2 Days in Paris
3,2 Days in New York (2012),2 Days in...,2012.0,2 Days in New York
4,8mm (1999),8mm,1999.0,8mm
5,8mm 2 (2005) (V),8mm,2005.0,8mm 2
10,28 Days Later (2002),28 Days Later,2002.0,28 Days Later
11,28 Weeks Later (2007),28 Days Later,2007.0,28 Weeks Later
12,30 Days of Night (2007),30 Days of Night,2007.0,30 Days of Night
13,30 Days of Night: Dark Days (2010),30 Days of Night,2010.0,30 Days of Night: Dark Days
18,47 Meters Down (2017),47 Meters Down,2017.0,47 Meters Down
19,47 Meters Down: Uncaged (2019),47 Meters Down,2019.0,47 Meters Down: Uncaged
22,100 Girls (2000),100 Girls,2000.0,100 Girls
23,100 Women (2002) (aka Girl Fever),100 Girls,2002.0,100 Women
25,101 Dalmatians II: Patch's London Adventure (2...,101 Dalmatians (1961 series) (A) *,2003.0,101 Dalmatians II: Patch's London Adventure
26,101 Dalmatians (1996),101 Dalmatians (1996 series),1996.0,101 Dalmatians
27,102 Dalmatians (2000),101 Dalmatians (1996 series),2000.0,102 Dalmatians
28,300 (2007),300,2007.0,300
29,300: Rise of an Empire (2014) (prequel),300,2014.0,300: Rise of an Empire
30,500 Years Later (2005),500 Years Later,2005.0,500 Years Later

In [317]:
#test_df.apply(lambda x: print(x['title_clean'], x['date']), axis=1)

In [351]:
#test_df['date'].apply(str)

In [371]:
final_df = test_df.merge(test_df.apply(lambda x: pd.Series(query_api(x['title_clean'], x['date'])), axis=1), 
             left_index=True, right_index=True)

<Response [200]>
{'Title': '00 Schneider - Jagd auf Nihil Baxter', 'Year': '1994', 'Rated': 'N/A', 'Released': '22 Dec 1994', 'Runtime': '90 min', 'Genre': 'Comedy', 'Director': 'Helge Schneider', 'Writer': 'Helge Schneider (film), Brötchen (screenplay)', 'Actors': 'Helge Schneider, Helmut Körschgen, Andreas Kunze, Werner Abrolat', 'Plot': 'Detective 00 Schneider has to return from retirement to catch a mad art collector.', 'Language': 'German', 'Country': 'Germany', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BOTQzMzQzMTkyNV5BMl5BanBnXkFtZTcwNjI4NTAyMQ@@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.1/10'}], 'Metascore': 'N/A', 'imdbRating': '7.1', 'imdbVotes': '2,428', 'imdbID': 'tt0109000', 'Type': 'movie', 'DVD': 'N/A', 'BoxOffice': 'N/A', 'Production': 'N/A', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '00 Schneider - Jagd auf Nihil Baxter', 'Year': '1994', 'Rated': 'N/A', 'Released': '22 Dec 1994', 'Runtime': '90 min', 'Genre': 'Comedy', 'Director': 'Helge Schneider', 'Writer': 'Helge Schneider (film), Brötchen (screenplay)', 'Actors': 'Helge Schneider, Helmut Körschgen, Andreas Kunze, Werner Abrolat', 'Plot': 'Detective 00 Schneider has to return from retirement to catch a mad art collector.', 'Language': 'German', 'Country': 'Germany', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BOTQzMzQzMTkyNV5BMl5BanBnXkFtZTcwNjI4NTAyMQ@@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.1/10'}], 'Metascore': 'N/A', 'imdbRating': '7.1', 'imdbVotes': '2,428', 'imdbID': 'tt0109000', 'Type': 'movie', 'DVD': 'N/A', 'BoxOffice': 'N/A', 'Production': 'N/A', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Response': 'False', 'Error': 'Movie not found!'}
<Response [200]>
{'Title': '2 Days in Paris', 'Year': '2007', 'Rated': 'R', 'Released': '31 Aug 2007', 'Runtime': '96 min', 'Genre': 'Comedy, Drama, Romance', 'Director': 'Julie Delpy', 'Writer': 'Julie Delpy', 'Actors': 'Adam Goldberg, Julie Delpy, Daniel Brühl, Marie Pillet', 'Plot': "Marion and Jack try to rekindle their relationship with a visit to Paris, home of Marion's parents -- and several of her ex-boyfriends.", 'Language': 'English, French', 'Country': 'France, Germany', 'Awards': '2 wins & 5 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjAyNTY3NTcyOF5BMl5BanBnXkFtZTcwMTcyMjM1MQ@@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.8/10'}, {'Source': 'Rotten Tomatoes', 'Value': '87%'}, {'Source': 'Metacritic', 'Value': '67/100'}], 'Metascore': '67', 'imdbRating': '6.8', 'imdbVotes': '29,488', 'imdbID': 'tt0841044', 'Type': 'movie', 'DVD': '05 Feb 2008', 'BoxOffice': '$4,215,065', 'Production': 'Samuel Goldwyn Film/Red Envelope', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '2 Days in New York', 'Year': '2012', 'Rated': 'R', 'Released': '28 Mar 2012', 'Runtime': '96 min', 'Genre': 'Comedy, Drama, Romance', 'Director': 'Julie Delpy', 'Writer': 'Julie Delpy (scenario), Alexia Landeau (scenario), Alexandre Nahon (participation), Julie Delpy (based on original characters created by), Alexandre Nahon (scenario)', 'Actors': 'Chris Rock, Julie Delpy, Albert Delpy, Alexia Landeau', 'Plot': "Manhattan couple Marion and Mingus, who each have children from prior relationships, find their comfortable family dynamic jostled by a visit from Marion's relatives.", 'Language': 'English, French, Italian', 'Country': 'France, Germany, Belgium', 'Awards': '1 win & 1 nomination.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjI5NTU2MDgyNl5BMl5BanBnXkFtZTcwNzk4NDI5Nw@@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.0/10'}, {'Source': 'Rotten Tomatoes', 'Value': '66%'}, {'Source': 'Metacritic', 'Value': '61/100'}], 'Metascore': '61', 'imdbRating': '6.0', 'imdbVotes': '13,718', 'imdbID': 'tt1602472', 'Type': 'movie', 'DVD': '13 Nov 2012', 'BoxOffice': '$500,000', 'Production': 'Magnolia Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '8MM', 'Year': '1999', 'Rated': 'R', 'Released': '26 Feb 1999', 'Runtime': '123 min', 'Genre': 'Crime, Drama, Mystery, Thriller', 'Director': 'Joel Schumacher', 'Writer': 'Andrew Kevin Walker', 'Actors': 'Nicolas Cage, Joaquin Phoenix, James Gandolfini, Peter Stormare', 'Plot': 'A private investigator is hired to discover if a "snuff film" is authentic or not.', 'Language': 'English', 'Country': 'Germany, USA', 'Awards': '2 wins & 2 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNTNiMzAxZGMtZGYwZi00NWVmLTgyNmYtMGIwZGJhNzE0NmJjXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.5/10'}, {'Source': 'Rotten Tomatoes', 'Value': '22%'}, {'Source': 'Metacritic', 'Value': '19/100'}], 'Metascore': '19', 'imdbRating': '6.5', 'imdbVotes': '120,927', 'imdbID': 'tt0134273', 'Type': 'movie', 'DVD': '22 May 2001', 'BoxOffice': 'N/A', 'Production': 'Columbia Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '8MM 2', 'Year': '2005', 'Rated': 'R', 'Released': '22 Nov 2005', 'Runtime': '106 min', 'Genre': 'Mystery, Thriller', 'Director': 'J.S. Cardone', 'Writer': 'Robert Sullivan (screenplay), Dylan Tarason (story)', 'Actors': 'Johnathon Schaech, Lori Heuring, Bruce Davison, Julie Benz', 'Plot': 'An American diplomat and his fiancée venture into the sordid underworld of sex and pornography in Budapest, Hungary to find out who is blackmailing them with a porno video taken of them with a prostitute.', 'Language': 'English, Hungarian', 'Country': 'USA, Hungary', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjA4OTU5OTE0MF5BMl5BanBnXkFtZTgwNjYyNjAwNzE@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '4.5/10'}], 'Metascore': 'N/A', 'imdbRating': '4.5', 'imdbVotes': '4,249', 'imdbID': 'tt0448172', 'Type': 'movie', 'DVD': '22 Nov 2005', 'BoxOffice': 'N/A', 'Production': 'Sony Pictures Entertainment', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '28 Days Later...', 'Year': '2002', 'Rated': 'R', 'Released': '27 Jun 2003', 'Runtime': '113 min', 'Genre': 'Drama, Horror, Sci-Fi, Thriller', 'Director': 'Danny Boyle', 'Writer': 'Alex Garland', 'Actors': 'Alex Palmer, Bindu De Stoppani, Jukka Hiltunen, David Schneider', 'Plot': 'Four weeks after a mysterious, incurable virus spreads throughout the UK, a handful of survivors try to find sanctuary.', 'Language': 'English, Spanish', 'Country': 'UK, Spain', 'Awards': '10 wins & 31 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYTFkM2ViMmQtZmI5NS00MjQ2LWEyN2EtMTI1ZmNlZDU3MTZjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'}, {'Source': 'Rotten Tomatoes', 'Value': '87%'}, {'Source': 'Metacritic', 'Value': '73/100'}], 'Metascore': '73', 'imdbRating': '7.6', 'imdbVotes': '367,331', 'imdbID': 'tt0289043', 'Type': 'movie', 'DVD': '21 Oct 2003', 'BoxOffice': '$44,900,469', 'Production': 'Fox Searchlight Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '28 Weeks Later', 'Year': '2007', 'Rated': 'R', 'Released': '11 May 2007', 'Runtime': '100 min', 'Genre': 'Horror, Sci-Fi', 'Director': 'Juan Carlos Fresnadillo', 'Writer': 'Rowan Joffe (screenplay), Juan Carlos Fresnadillo (screenplay), Enrique López Lavigne (screenplay), Jesús Olmo (screenplay)', 'Actors': 'Robert Carlyle, Rose Byrne, Jeremy Renner, Harold Perrineau', 'Plot': 'Six months after the rage virus was inflicted on the population of Great Britain, the US Army helps to secure a small area of London for the survivors to repopulate and start again. But not everything goes according to plan.', 'Language': 'English', 'Country': 'UK, Spain', 'Awards': '2 wins & 13 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjA5NjE2NDI0OF5BMl5BanBnXkFtZTgwNzU0NzQyMTI@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.0/10'}, {'Source': 'Rotten Tomatoes', 'Value': '71%'}, {'Source': 'Metacritic', 'Value': '78/100'}], 'Metascore': '78', 'imdbRating': '7.0', 'imdbVotes': '253,546', 'imdbID': 'tt0463854', 'Type': 'movie', 'DVD': '09 Oct 2007', 'BoxOffice': '$28,586,503', 'Production': 'Fox Atomic', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '30 Days of Night', 'Year': '2007', 'Rated': 'R', 'Released': '19 Oct 2007', 'Runtime': '113 min', 'Genre': 'Action, Horror, Thriller', 'Director': 'David Slade', 'Writer': 'Steve Niles (screenplay), Stuart Beattie (screenplay), Brian Nelson (screenplay), Steve Niles (comic), Ben Templesmith (comic)', 'Actors': 'Josh Hartnett, Melissa George, Danny Huston, Ben Foster', 'Plot': 'After an Alaskan town is plunged into darkness for a month, it is attacked by a bloodthirsty gang of vampires.', 'Language': 'English', 'Country': 'USA, New Zealand', 'Awards': '13 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZmE2ODFlZjctOWZlZi00MGVkLTk5NDctYWZmMWQyOTczNjYzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.6/10'}, {'Source': 'Rotten Tomatoes', 'Value': '51%'}, {'Source': 'Metacritic', 'Value': '53/100'}], 'Metascore': '53', 'imdbRating': '6.6', 'imdbVotes': '161,027', 'imdbID': 'tt0389722', 'Type': 'movie', 'DVD': '19 Feb 2008', 'BoxOffice': '$39,568,996', 'Production': 'Sony Pictures/Columbia', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '30 Days of Night: Dark Days', 'Year': '2010', 'Rated': 'R', 'Released': '05 Oct 2010', 'Runtime': '92 min', 'Genre': 'Horror, Thriller', 'Director': 'Ben Ketai', 'Writer': 'Steve Niles (screenplay), Ben Ketai (screenplay), Steve Niles (comic), Ben Templesmith (comic)', 'Actors': 'Kiele Sanchez, Rhys Coiro, Diora Baird, Harold Perrineau', 'Plot': 'After surviving the incidents in Barrow, Alaska, Stella Oleson relocates to Los Angeles, where she intentionally attracts the attention of the local vampire population in order to avenge the death of her husband, Eben.', 'Language': 'English', 'Country': 'USA', 'Awards': '2 wins.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY3ODMxODIwNl5BMl5BanBnXkFtZTgwMDYyODAwNzE@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '4.4/10'}, {'Source': 'Rotten Tomatoes', 'Value': '17%'}], 'Metascore': 'N/A', 'imdbRating': '4.4', 'imdbVotes': '12,126', 'imdbID': 'tt1320304', 'Type': 'movie', 'DVD': '05 Oct 2010', 'BoxOffice': 'N/A', 'Production': 'SPE Acquisitions', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '47 Meters Down', 'Year': '2017', 'Rated': 'PG-13', 'Released': '16 Jun 2017', 'Runtime': '89 min', 'Genre': 'Adventure, Drama, Horror, Thriller', 'Director': 'Johannes Roberts', 'Writer': 'Johannes Roberts, Ernest Riera', 'Actors': 'Mandy Moore, Claire Holt, Chris Johnson, Yani Gellman', 'Plot': 'Two sisters vacationing in Mexico are trapped in a shark cage at the bottom of the ocean. With less than an hour of oxygen left and great white sharks circling nearby, they must fight to survive.', 'Language': 'English, Spanish', 'Country': 'UK', 'Awards': '2 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYTcyMDRiNDQtODRkMy00YjU0LWEwYTEtMzk3NzIzODYzMjU2XkEyXkFqcGdeQXVyMTk5MzE1MTY@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.6/10'}, {'Source': 'Rotten Tomatoes', 'Value': '53%'}, {'Source': 'Metacritic', 'Value': '52/100'}], 'Metascore': '52', 'imdbRating': '5.6', 'imdbVotes': '46,796', 'imdbID': 'tt2932536', 'Type': 'movie', 'DVD': '26 Sep 2017', 'BoxOffice': '$44,305,642', 'Production': 'Entertainment Studios Motion Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '47 Meters Down: Uncaged', 'Year': '2019', 'Rated': 'PG-13', 'Released': '16 Aug 2019', 'Runtime': '90 min', 'Genre': 'Adventure, Drama, Horror, Thriller', 'Director': 'Johannes Roberts', 'Writer': 'Ernest Riera, Johannes Roberts', 'Actors': 'Sophie Nélisse, Corinne Foxx, Brianne Tju, Sistine Rose Stallone', 'Plot': "Four teen girls diving in a ruined underwater city quickly learn they've entered the territory of the deadliest shark species in the claustrophobic labyrinth of submerged caves.", 'Language': 'English', 'Country': 'UK, USA', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMDc1MmVjMDQtOGU3OS00OTJkLWJmOGQtNDMzMWRjNDAzY2Y2XkEyXkFqcGdeQXVyMTk5MzE1MTY@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.0/10'}, {'Source': 'Rotten Tomatoes', 'Value': '44%'}, {'Source': 'Metacritic', 'Value': '43/100'}], 'Metascore': '43', 'imdbRating': '5.0', 'imdbVotes': '16,941', 'imdbID': 'tt7329656', 'Type': 'movie', 'DVD': '29 Oct 2019', 'BoxOffice': 'N/A', 'Production': 'Entertainment Studios Motion Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '100 Girls', 'Year': '2000', 'Rated': 'R', 'Released': '01 Sep 2000', 'Runtime': '94 min', 'Genre': 'Comedy, Romance', 'Director': 'Michael Davis', 'Writer': 'Michael Davis', 'Actors': 'Jonathan Tucker, Emmanuelle Chriqui, James DeBello, Katherine Heigl', 'Plot': "Matt spends the night with a girl in an elevator during power outage in a girls' college dorm. He never sees her. Waking up in the morning, panties are all that's left of her. How does he find her in a building with 100 girls?", 'Language': 'English', 'Country': 'USA', 'Awards': '2 wins & 2 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTA0MjA5MjM3NDFeQTJeQWpwZ15BbWU4MDMxODU4ODkx._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.8/10'}, {'Source': 'Rotten Tomatoes', 'Value': '60%'}], 'Metascore': 'N/A', 'imdbRating': '5.8', 'imdbVotes': '20,437', 'imdbID': 'tt0214388', 'Type': 'movie', 'DVD': '11 Sep 2001', 'BoxOffice': 'N/A', 'Production': 'Dream Entertainment', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Response': 'False', 'Error': 'Movie not found!'}
<Response [200]>
{'Response': 'False', 'Error': 'Movie not found!'}
<Response [200]>
{'Title': '101 Dalmatians', 'Year': '1996', 'Rated': 'G', 'Released': '27 Nov 1996', 'Runtime': '103 min', 'Genre': 'Adventure, Comedy, Crime, Family', 'Director': 'Stephen Herek', 'Writer': 'Dodie Smith (novel), John Hughes (screenplay)', 'Actors': 'Glenn Close, Jeff Daniels, Joely Richardson, Joan Plowright', 'Plot': 'An evil high-fashion designer plots to steal Dalmatian puppies in order to make an extravagant fur coat, but instead creates an extravagant mess.', 'Language': 'English, Spanish', 'Country': 'USA, UK', 'Awards': 'Nominated for 1 Golden Globe. Another 3 wins & 9 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMGI2NTQ2N2EtNDExMS00OWM2LTkzZWItZGUzY2M2MDFjODk0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.7/10'}, {'Source': 'Rotten Tomatoes', 'Value': '42%'}, {'Source': 'Metacritic', 'Value': '49/100'}], 'Metascore': '49', 'imdbRating': '5.7', 'imdbVotes': '98,484', 'imdbID': 'tt0115433', 'Type': 'movie', 'DVD': '21 Apr 1998', 'BoxOffice': 'N/A', 'Production': 'Buena Vista Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '102 Dalmatians', 'Year': '2000', 'Rated': 'G', 'Released': '22 Nov 2000', 'Runtime': '100 min', 'Genre': 'Adventure, Comedy, Family', 'Director': 'Kevin Lima', 'Writer': 'Dodie Smith (novel), Kristen Buckley (story), Brian Regan (story), Kristen Buckley (screenplay), Brian Regan (screenplay), Bob Tzudiker (screenplay), Noni White (screenplay)', 'Actors': 'Glenn Close, Gérard Depardieu, Ioan Gruffudd, Alice Evans', 'Plot': 'Cruella DeVil gets out of prison and goes after the puppies once more.', 'Language': 'English', 'Country': 'USA, UK', 'Awards': 'Nominated for 1 Oscar. Another 1 win & 7 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BYmEzOTcxNzUtYmVjMS00MzNiLWJjNTEtOTY3MTE2ZjVkMGQ5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '4.9/10'}, {'Source': 'Rotten Tomatoes', 'Value': '31%'}, {'Source': 'Metacritic', 'Value': '35/100'}], 'Metascore': '35', 'imdbRating': '4.9', 'imdbVotes': '33,864', 'imdbID': 'tt0211181', 'Type': 'movie', 'DVD': '03 Apr 2001', 'BoxOffice': '$65,406,212', 'Production': 'Buena Vista Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': 'The 300: Fact or Fiction?', 'Year': '2007', 'Rated': 'N/A', 'Released': '29 Aug 2007', 'Runtime': '24 min', 'Genre': 'Documentary, Short', 'Director': 'N/A', 'Writer': 'N/A', 'Actors': 'Victor Davis Hanson, Zack Snyder, Frank Miller, Bettany Hughes', 'Plot': 'A look at the historical reality behind the film 300 (2006)', 'Language': 'English', 'Country': 'USA', 'Awards': 'N/A', 'Poster': 'N/A', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'}], 'Metascore': 'N/A', 'imdbRating': '6.1', 'imdbVotes': '37', 'imdbID': 'tt1252377', 'Type': 'movie', 'DVD': 'N/A', 'BoxOffice': 'N/A', 'Production': 'N/A', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '300: Rise of an Empire', 'Year': '2014', 'Rated': 'R', 'Released': '07 Mar 2014', 'Runtime': '102 min', 'Genre': 'Action, Drama', 'Director': 'Noam Murro', 'Writer': 'Zack Snyder (screenplay), Kurt Johnstad (screenplay), Frank Miller (graphic novel "Xerxes")', 'Actors': 'Sullivan Stapleton, Eva Green, Lena Headey, Hans Matheson', 'Plot': 'Greek general Themistokles leads the charge against invading Persian forces led by mortal-turned-god Xerxes and Artemisia, vengeful commander of the Persian navy.', 'Language': 'English', 'Country': 'USA', 'Awards': '2 wins & 7 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTEwNTU2MjAwMDdeQTJeQWpwZ15BbWU3MDk2Njc2Njk@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.2/10'}, {'Source': 'Rotten Tomatoes', 'Value': '44%'}, {'Source': 'Metacritic', 'Value': '48/100'}], 'Metascore': '48', 'imdbRating': '6.2', 'imdbVotes': '275,286', 'imdbID': 'tt1253863', 'Type': 'movie', 'DVD': '24 Jun 2014', 'BoxOffice': '$91,024,535', 'Production': 'Warner Bros. Pictures', 'Website': 'N/A', 'Response': 'True'}
<Response [200]>
{'Title': '500 Years Later', 'Year': '2005', 'Rated': 'Not Rated', 'Released': '24 Feb 2005', 'Runtime': '106 min', 'Genre': 'Documentary', 'Director': 'Owen Alik Shahadah', 'Writer': 'M.K. Asante', 'Actors': 'Kolfi Adu, Sona Jobarteh, Hunter Adams III, Hakim Adi', 'Plot': 'Crime, drugs, HIV/AIDS, poor education, inferiority complex, low expectation, poverty, corruption, poor health, and underdevelopment plagues people of African descent globally - Why? 500 ...', 'Language': 'English', 'Country': 'UK, USA', 'Awards': '2 wins.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjE5MDAzNDYzOV5BMl5BanBnXkFtZTcwMTA0MjgyMQ@@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.8/10'}], 'Metascore': 'N/A', 'imdbRating': '6.8', 'imdbVotes': '179', 'imdbID': 'tt0444593', 'Type': 'movie', 'DVD': '08 Jan 2008', 'BoxOffice': 'N/A', 'Production': 'Codeblack TV', 'Website': 'N/A', 'Response': 'True'}

In [372]:
series_names = final_df['series'].unique()

In [377]:
final_df.loc[df['series'] == series_names[2], ['imdb', 'title_clean']].set_index('title_clean').plot(kind='bar')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.